### ISSUE TITLE
Webpack Crash when import trowel buttons

### ISSUE THREAD

**Issue by SilentKernel** [FriendsOfTrowel/Buttons#6]
Hi

When i try to import button in my  main.scss file webpack crash instantly.

There is my environment : 
```
macOS : 10.12.6
node: 6.11.2
webpack: 3.4.1
webpack-encore: 0.12.0
node-sass: 4.5.3
libsass: 3.5.0.beta.2
```
I tried to import sassy-maps (import shown in the README of this repo but not on trowel.github.io).
I also tried to upgrade node to a non-lts version (8)

But i can't get it to work.

My project is available here -> https://github.com/SilentKernel/blog

![screenshot 2017-08-06 18 24 09](https://user-images.githubusercontent.com/7534223/29005250-0a5be7b8-7ad7-11e7-97c7-89c5c5a735e2.png)

**Comment by LoicGoyet** [comment]
Woops, sorry for seeing that issue just now. I'll get a look during the weekend.

About Sassy-maps, it used to be required to import it into your main scss file before trowel-core, but it is not anymore. We missed out to remote it from the README

**Comment by SilentKernel** [comment]
No problem for the time

That's why i understood for Sassy-maps but wanted to give max infos as possible
